import Head from 'next/head';
import Image from 'next/image';
import Banner from '../components/banner/banner';
import styles from '../styles/Home.module.css';

export default function Home() {
	const handleOnBannerBtnClick = () => {
		console.log('Button is clicked');
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Coffee Connoisseur</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<Banner buttonText='View stores nearby' handleOnClick={handleOnBannerBtnClick} />
				<Image
					priority={true}
					className={styles.heroImage}
					alt=''
					src='/static/hero-image.png'
					width={700}
					height={400}
				/>
			</main>
		</div>
	);
}
